---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9

suites:
  - name: default
    run_list:
      - recipe[bm-base::file_server]
      - recipe[sybase::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      sybase:
        source_archive: "ase157_linuxx86-64.tgz"
        source_archive_path: "/mnt/atlas/software/Databases/Sybase/Sybase_ASE_15.7/ase157_linuxx86-64.tgz"
        rsp:
          sybase_product_license_type: "developer"
          sybase_notification_smtp_hostname: "smtp.bluemedora.localnet"
          sybase_notification_recipient_email: "engops@bluemedora.com"
          sy_cfg_ase_password: "password"
          sy_cfg_sm_password: "password"
          config_scc_csi_sccadmin_pwd: "passowrd"
          config_scc_csi_uafadmin_pwd: "password"

    driver:
      network:
        - ["public_network", {bridge: 'en0: Wi-Fi (AirPort)', type: dhcp}]
